// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LensAndLight.Migrations
{
    [DbContext(typeof(PhotographyContext))]
    [Migration("20260508212746_UpdateSeedDataWithImages")]
    partial class UpdateSeedDataWithImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Capturing your 'I Do' moments forever.",
                            Name = "Weddings"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Celebrate your hard-earned milestone.",
                            Name = "Graduation"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Single person and family lifestyle sessions.",
                            Name = "Portraits"
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Proms, parties, and special gatherings.",
                            Name = "Events"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "Sweet, tiny memories for new parents.",
                            Name = "Newborn"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 160.00m,
                            Title = "Elegant Wedding Vol 1"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 170.00m,
                            Title = "Elegant Wedding Vol 2"
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 180.00m,
                            Title = "Elegant Wedding Vol 3"
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 190.00m,
                            Title = "Elegant Wedding Vol 4"
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 200.00m,
                            Title = "Elegant Wedding Vol 5"
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Description = "Full day coverage with a romantic, airy edit.",
                            ImageUrl = "/images/wedding.jpg",
                            Price = 210.00m,
                            Title = "Elegant Wedding Vol 6"
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 220.00m,
                            Title = "Senior Glow Grad 1"
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 230.00m,
                            Title = "Senior Glow Grad 2"
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 240.00m,
                            Title = "Senior Glow Grad 3"
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 250.00m,
                            Title = "Senior Glow Grad 4"
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 260.00m,
                            Title = "Senior Glow Grad 5"
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 2,
                            Description = "Celebrate your graduation with sunshine and smiles!",
                            ImageUrl = "/images/grad.jpg",
                            Price = 270.00m,
                            Title = "Senior Glow Grad 6"
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 280.00m,
                            Title = "Classic Portrait 1"
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 290.00m,
                            Title = "Classic Portrait 2"
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 300.00m,
                            Title = "Classic Portrait 3"
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 310.00m,
                            Title = "Classic Portrait 4"
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 320.00m,
                            Title = "Classic Portrait 5"
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 3,
                            Description = "Perfect for LinkedIn, social media, or just because!",
                            ImageUrl = "/images/portrait.jpg",
                            Price = 330.00m,
                            Title = "Classic Portrait 6"
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 340.00m,
                            Title = "Prom Night Magic 1"
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 350.00m,
                            Title = "Prom Night Magic 2"
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 360.00m,
                            Title = "Prom Night Magic 3"
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 370.00m,
                            Title = "Prom Night Magic 4"
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 380.00m,
                            Title = "Prom Night Magic 5"
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 4,
                            Description = "Capture the sparkle of your big night with friends.",
                            ImageUrl = "/images/prom.jpg",
                            Price = 390.00m,
                            Title = "Prom Night Magic 6"
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 400.00m,
                            Title = "Tiny Toes Newborn 1"
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 410.00m,
                            Title = "Tiny Toes Newborn 2"
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 420.00m,
                            Title = "Tiny Toes Newborn 3"
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 430.00m,
                            Title = "Tiny Toes Newborn 4"
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 440.00m,
                            Title = "Tiny Toes Newborn 5"
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 5,
                            Description = "Soft, cozy shots of your newest little love.",
                            ImageUrl = "/images/newborn.jpg",
                            Price = 450.00m,
                            Title = "Tiny Toes Newborn 6"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
