// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LensAndLight.Migrations
{
    [DbContext(typeof(PhotographyContext))]
    partial class PhotographyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Forever starts here.",
                            Name = "Weddings"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 101m,
                            Title = "Package 1"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 102m,
                            Title = "Package 2"
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 103m,
                            Title = "Package 3"
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 104m,
                            Title = "Package 4"
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 105m,
                            Title = "Package 5"
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 106m,
                            Title = "Package 6"
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 107m,
                            Title = "Package 7"
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 108m,
                            Title = "Package 8"
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 109m,
                            Title = "Package 9"
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 110m,
                            Title = "Package 10"
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 111m,
                            Title = "Package 11"
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 112m,
                            Title = "Package 12"
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 113m,
                            Title = "Package 13"
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 114m,
                            Title = "Package 14"
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 115m,
                            Title = "Package 15"
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 116m,
                            Title = "Package 16"
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 117m,
                            Title = "Package 17"
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 118m,
                            Title = "Package 18"
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 119m,
                            Title = "Package 19"
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 120m,
                            Title = "Package 20"
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 121m,
                            Title = "Package 21"
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 122m,
                            Title = "Package 22"
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 123m,
                            Title = "Package 23"
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 124m,
                            Title = "Package 24"
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 125m,
                            Title = "Package 25"
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 126m,
                            Title = "Package 26"
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 127m,
                            Title = "Package 27"
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 128m,
                            Title = "Package 28"
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 129m,
                            Title = "Package 29"
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 1,
                            Description = "High quality shots.",
                            Price = 130m,
                            Title = "Package 30"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
